version: '3'
services:
  my-mongo:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=nestjs_mongo
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=secreta123
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db
